import type { Metadata } from "next";
import { Inter, Nabla } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import Navbar from "@/components/Navbar";
import { MyFooter } from "@/components/MyFooter";
import { headers } from "next/headers";
import { useRouter } from "next/router";
import path from "path";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // BELOW : only works on server components
  // const headersList = headers();
  // const pathname = headersList.get("x-invoke-path") || "";
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-black`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* {pathname !== "/dashboard" && <Navbar />} */}
          <Navbar />
          {children}
          {/* {pathname !== "/dashboard" && <MyFooter />} */}
          <MyFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
